// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hackathon.Database;

#nullable disable

namespace hackathon.Migrations
{
    [DbContext(typeof(HackathonContext))]
    [Migration("20240207035152_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("hackathon.Database.Model.ImportedShell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoteDiscoveryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteRegistryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ImportedShells");
                });
#pragma warning restore 612, 618
        }
    }
}
